### ISSUE TITLE
为什么头文件都是无法打开源文件…

### ISSUE THREAD

**Issue by Nuyoah0525** [lanomw/qt-zmyy#1]

**Comment by lanomw** [comment]
不太清楚你说的问题，我项目是clion写的，utf8编码

**Comment by Nuyoah0525** [comment]
额 我vscode打开的 头文件都标红 设置了半天头文件路径也没好 尬

**Comment by lanomw** [comment]
编辑器配置没对吧，不清楚vscode怎么配

**Comment by NoIgnore** [comment]
可以发布exe文件吗

**Comment by lanomw** [comment]
> 可以发布exe文件吗

需要cmakelists.txt里面配置，不过我不会配置这个

**Comment by Codgi-123** [comment]
> 可以发布exe文件吗

虽然我也不会配置，但是我用其他方法打包出来了

**Comment by NoIgnore** [comment]
> 

可以分享一下吗

**Comment by Codgi-123** [comment]
@lanomw 请问下设置好之后能直接使用吗，因为我看到 `README` 里面提到疫苗数量获取那里没解决

**Comment by lanomw** [comment]
> @lanomw 请问下设置好之后能直接使用吗，因为我看到 `README` 里面提到疫苗数量获取那里没解决
哪个问题还没有解决，可以的话自己改下，剩下的问题应该不多

**Comment by lichenchen85** [comment]
> @lanomw 请问下设置好之后能直接使用吗，因为我看到 `README` 里面提到疫苗数量获取那里没解决

请问一下，你跑成功这个代码了吗

**Comment by lanomw** [comment]
我重新更新一下，我这边测试流程通了，目前需要测试下九价定时预约这个有没有问题

**Comment by lanomw** [comment]
九价的群有没有啊，我之前加的群没了😂

**Comment by Nuyoah0525** [comment]
> 

有联系方式吗

**Comment by Nuyoah0525** [comment]
> 九价的群有没有啊，我之前加的群没了😂

有联系方式吗

**Comment by fjqken** [comment]
兄弟解决了吗，我也都报这个错
