### ISSUE TITLE
signature的获取方式

### ISSUE THREAD

**Issue by chen1044316902** [lanomw/qt-zmyy#12]
文档中说了两种方式获取signature，通过CE或者通过Cookie，我想咨询下通过Cookie怎么获取signature呢

**Comment by lanomw** [comment]
cookie使用jwt解出来，然后把val的值base64解码。从第九个字符开始取16位

**Comment by chen1044316902** [comment]
666

**Comment by chen1044316902** [comment]
![image](https://user-images.githubusercontent.com/31918675/154878141-a1a20965-fad2-4c9b-8084-b5d51668e110.png)
用base64解密不了呀？ 这个是有什么问题吗

**Comment by lanomw** [comment]
解不了就换一个网站，有些网站解不了部分字符






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Nuyoah ***@***.***&gt;; 
发送时间: 2022年2月21日(星期一) 上午10:17
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [lanomw/qt-zmyy] signature的获取方式 (Issue #12)





 

 用base64解密不了呀？ 这个是有什么问题吗
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by chen1044316902** [comment]
好的 多谢
