### ISSUE TITLE
ERROR 【二级分类】 99  TLS initialization failed 

### ISSUE THREAD

**Issue by taiheqin** [lanomw/qt-zmyy#15]
![image](https://user-images.githubusercontent.com/48525034/155846099-50131e3b-ac33-402f-b115-3ea74ae9fc2a.png)

**Comment by dengjianzhong** [comment]
我也遇到了同样的问题

**Comment by taiheqin** [comment]
taihe收到

**Comment by lz5921** [comment]
> ![image](https://user-images.githubusercontent.com/48525034/155846099-50131e3b-ac33-402f-b115-3ea74ae9fc2a.png)

需要openssl

**Comment by taiheqin** [comment]
taihe收到

**Comment by lqzhgood** [comment]
有人能详细说说怎么做么？

我从 https://slproweb.com/products/Win32OpenSSL.html 下载 `Win32 OpenSSL v1.1.1s Light` 安装后
拷贝 `libssl-1_1.dll` `libcrypto-1_1.dll` 到 exe 目录也依然报错 `TLS initialization failed 
` 。exe 从 V1.0 Release 下载后解压的。

**Comment by taiheqin** [comment]
taihe收到
