### ISSUE TITLE
Windows 下编译构建

### ISSUE THREAD

**Issue by JQLYM** [lanomw/qt-zmyy#17]
windows 编译构建，对于环境有哪些要求，需要哪些软件，哪些配置，软件版本等有什么要求限制，能不能提供一下windows编译的指导

**Comment by ZdDroid** [comment]
QT5.15.2 使用 VS2022成功编译:
1.安装 QT & QTVS 插件 
2.新建 QT 工程,把源文件导入 
3.修复 WeChatUtil.cpp 中一个 VC 不支持的语法错误 .

![image](https://user-images.githubusercontent.com/43038779/156891527-25209e1c-4c17-4664-aeb2-dd4aeb7903c2.png)
