### ISSUE TITLE
求大佬，黄牛的联系方式

### ISSUE THREAD

**Issue by MrsLi** [lanomw/qt-zmyy#19]
对象找黄牛约上了(我太慢了ToT)
 求黄牛联系方式？

**Comment by qaz4042** [comment]
兄弟,同求额

**Comment by qaz4042** [comment]
wx号吗? 多谢多谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年3月9日(星期三) 凌晨0:59
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [lanomw/qt-zmyy] 求大佬，黄牛的联系方式 (Issue #19)





 
SYM0920
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lanomw** [comment]
wx; lescsno10422
不清楚现在可以帮忙约不

**Comment by Littlecousin** [comment]
@lanomw 你好，能不能询问下你女友的姓名（原谅我的不礼貌），黄牛要验值是不是钓鱼的！！/裂开
