### ISSUE TITLE
dll丢失

### ISSUE THREAD

**Issue by Codgi-123** [lanomw/qt-zmyy#2]
请教一下，构建后运行exe提示 `qt5network.dll` 丢失，请问怎么解决

**Comment by lanomw** [comment]
配置漏了这个，重新拉下代码

**Comment by Codgi-123** [comment]
辛苦了，现在已经跑起来了

**Comment by Codgi-123** [comment]
额...貌似还有两个： `libgcc_s_seh-1.dll`  `libwinpthread-1.dll`

**Comment by lanomw** [comment]
这两个是编译器里面的库吧
看下这个：https://blog.csdn.net/qq_42467347/article/details/103669697?utm_medium=distribute.pc_relevant.none-task-blog-BlogCommendFromMachineLearnPai2-1.control&depth_1-utm_source=distribute.pc_relevant.none-task-blog-BlogCommendFromMachineLearnPai2-1.control

**Comment by Codgi-123** [comment]
搞定了，刚刚吃饭太急了没有点确定，新添加的环境变量没生效。再次感谢您

**Comment by lichenchen85** [comment]
> 搞定了，刚刚吃饭太急了没有点确定，新添加的环境变量没生效。再次感谢您

你好，有没有遇到过提交订单，299，显示缺少length字段
