### ISSUE TITLE
大佬，程序会崩溃、而且也链不上网络

### ISSUE THREAD

**Issue by PiscesYXT** [lanomw/qt-zmyy#21]
第一个BUG：填写cookie，点击设置cookie后就会直接退出；而且有一些时候也是这样子
第二个BUG： 程序打开，包括查询全部显示：99  TLS initialization failed ；已经按照大佬您说的dll放到相关的目录了还是不行。图片如下
![Uploading 3.jpg…]()

**Comment by PiscesYXT** [comment]
![3](https://user-images.githubusercontent.com/66818699/158181427-5ae94265-5816-480b-8d89-e05143046267.jpg)

**Comment by Wayen495984320** [comment]
一样的问题

**Comment by Wayen495984320** [comment]
已经解决 TLS initialization failed 错误现在就是在设置cookie这里崩溃
