### ISSUE TITLE
大佬，你的cheat engine获取signature的图片好像给错了。

### ISSUE THREAD

**Issue by akuya48** [lanomw/qt-zmyy#3]
![image](https://user-images.githubusercontent.com/73208839/151115363-b3a63601-a854-486b-8ff5-b8083965f420.png)
你给的是Charles配置的图片

**Comment by lanomw** [comment]
图片地址给错了，改正了

**Comment by akuya48** [comment]
@lanomw 大佬，这个还是抢不了呀，一到疫苗发放的时间 就直接报错 
![image](https://user-images.githubusercontent.com/73208839/151152215-415de4fe-f8ce-4b11-9c4e-afa1a1c39737.png)

**Comment by akuya48** [comment]
可能的原因是 在预约时间到达时，请求了能打疫苗的时间，结果当时小程序服务器压力过大，导致了返回值为空，直接结束了程序 之后建议改成日期顺延一天到两天。

**Comment by Nuyoah0525** [comment]
> 可能的原因是 在预约时间到达时，请求了能打疫苗的时间，结果当时小程序服务器压力过大，导致了返回值为空，直接结束了程序 之后建议改成日期顺延一天到两天。

老哥，你有进展嘛

**Comment by lichenchen85** [comment]
> 可能的原因是 在预约时间到达时，请求了能打疫苗的时间，结果当时小程序服务器压力过大，导致了返回值为空，直接结束了程序 之后建议改成日期顺延一天到两天。

![图片](https://user-images.githubusercontent.com/72535414/151184567-fdf3c59f-8a0e-4f94-8084-abbd760f7bfc.png)
大哥这个错误遇到过吗？
