### ISSUE TITLE
getProductDetail 方法中出错

### ISSUE THREAD

**Issue by Codgi-123** [lanomw/qt-zmyy#4]
如题，日志输出截图：
![image](https://user-images.githubusercontent.com/54504858/151360307-c625a1aa-0d06-45c3-beda-1276cda4b42a.png)

**Comment by lichenchen85** [comment]
我的和你的报错一样

**Comment by QQOQ** [comment]
有风控，具体还不太清楚，同样的请求信息放到postman或者代码请求测试就不行（偶尔会可以，但多数不行，换ip也一样），但是手动操作小程序就没问题
