### ISSUE TITLE
【建议】跳过访问 可接种时间 接口

### ISSUE THREAD

**Issue by Codgi-123** [lanomw/qt-zmyy#9]
个人觉得访问 `可接种时间` 接口在实际秒杀中是比较消耗时间的一个环节。可以提供选择按钮来让用户决定是否获取`可接种时间`，如果选择不获取接种时间则默认将可接种日期设置成当天日期的+1,+2,+3作为接种日期进行提交

**Comment by teg1c** [comment]
这个接口必须访问,不然获取加密的接口会失败

**Comment by wpwpahj** [comment]
可接种时间有地方可以提前获取到吗

**Comment by lanomw** [comment]
> 可接种时间有地方可以提前获取到吗

不行，接口那边开放了可预约才能获取到

**Comment by wpwpahj** [comment]
我这两天测试重庆的，获取接种时间都超过20秒

**Comment by wpwpahj** [comment]
> 

或者使用多线程，防止调用卡住，影响后续流程
